### ISSUE TITLE
Basic Calendar App functionality

### ISSUE THREAD

**Issue by jukrb0x** [jukrb0x/taskhorizon#11]
do with [react-big-calendar](https://github.com/jquense/react-big-calendar/)

## Stage 1
- [x] basic state management (add, _remove_), simple _Create New Event_ Card
- [x] State Sync with UI

## Stage 2
- [x] handle data type when retrieving items from _localStorage_
- [x] more state management (edit, remove)
- [x] event card, both for editing and creating events
- [x] resizer for sidebar (todo app)

## Stage 3
- [ ] Calendar Custom Styling with Tailwindcss
- [ ] enrich UI
- [ ] the event card can stick by the side of the event
